### ISSUE TITLE
Add .idea/ and venv/ to .gitignore

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/lesson-template#1]
Add these to .gitignore:

- .idea/ subdirectory created by PyCharm
- venv/ directory (a typical name for a virtual environment directory - maybe .venv/ too?)

**Comment by PipGrylls** [comment]
Done in https://github.com/Southampton-RSG-Training/lesson-template/commit/79a43a137aa7d6c2c40ea3e997a72d4f64531dc2
